"""sales return fixes

Revision ID: 0003895b2ccf
Revises: 1af9267ccc05
Create Date: 2026-02-13 11:00:49.445575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003895b2ccf'
down_revision: Union[str, Sequence[str], None] = '1af9267ccc05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_sale_return_lines', sa.Column('sale_line_id', sa.UUID(), nullable=True))
    op.alter_column('inventory_sale_return_lines', 'fifo_reversal_cost',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False)
    op.drop_constraint(op.f('inventory_sale_return_lines_product_id_fkey'), 'inventory_sale_return_lines', type_='foreignkey')
    op.create_foreign_key(None, 'inventory_sale_return_lines', 'inventory_sale_lines', ['sale_line_id'], ['id'])
    op.drop_column('inventory_sale_return_lines', 'unit_price')
    op.drop_column('inventory_sale_return_lines', 'product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_sale_return_lines', sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('inventory_sale_return_lines', sa.Column('unit_price', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'inventory_sale_return_lines', type_='foreignkey')
    op.create_foreign_key(op.f('inventory_sale_return_lines_product_id_fkey'), 'inventory_sale_return_lines', 'inventory_products', ['product_id'], ['id'])
    op.alter_column('inventory_sale_return_lines', 'fifo_reversal_cost',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True)
    op.drop_column('inventory_sale_return_lines', 'sale_line_id')
    # ### end Alembic commands ###
