"""add inventory sales returns and adjustments

Revision ID: 14e0c88394c9
Revises: 365033642075
Create Date: 2026-02-07 20:51:36.429433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14e0c88394c9'
down_revision: Union[str, Sequence[str], None] = '365033642075'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_adjustments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('adjustment_date', sa.Date(), nullable=False),
    sa.Column('adjustment_type', sa.Enum('INCREASE', 'DECREASE', name='inventory_adjustment_type'), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('is_posted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_sale_returns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=False),
    sa.Column('customer', sa.String(length=255), nullable=True),
    sa.Column('is_posted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_sales',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sale_date', sa.Date(), nullable=False),
    sa.Column('customer', sa.String(length=255), nullable=True),
    sa.Column('is_posted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_adjustment_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('adjustment_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('fifo_cost_used', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['adjustment_id'], ['inventory_adjustments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['inventory_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_sale_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sale_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('fifo_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['inventory_products.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['inventory_sales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_sale_return_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('return_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('fifo_reversal_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['inventory_products.id'], ),
    sa.ForeignKeyConstraint(['return_id'], ['inventory_sale_returns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_sale_return_lines')
    op.drop_table('inventory_sale_lines')
    op.drop_table('inventory_adjustment_lines')
    op.drop_table('inventory_sales')
    op.drop_table('inventory_sale_returns')
    op.drop_table('inventory_adjustments')
    # ### end Alembic commands ###
