"""create accounting periods

Revision ID: 5bb3a314b257
Revises: 9fc512b1ddb0
Create Date: 2026-02-07 17:12:29.752654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5bb3a314b257'
down_revision: Union[str, Sequence[str], None] = '9fc512b1ddb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounting_periods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('closed_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_unique_constraint('uq_account_code', 'accounts', ['code'])
    op.create_unique_constraint('uq_account_name', 'accounts', ['name'])
    op.alter_column('journal_entries', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('journal_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('journal_entries_journal_number_key'), 'journal_entries', type_='unique')
    op.create_index(op.f('ix_journal_entries_journal_number'), 'journal_entries', ['journal_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_journal_entries_journal_number'), table_name='journal_entries')
    op.create_unique_constraint(op.f('journal_entries_journal_number_key'), 'journal_entries', ['journal_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('journal_entries', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('journal_entries', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint('uq_account_name', 'accounts', type_='unique')
    op.drop_constraint('uq_account_code', 'accounts', type_='unique')
    op.drop_table('accounting_periods')
    # ### end Alembic commands ###
