"""create chart of accounts

Revision ID: 872998ef7d19
Revises: 3c7a9d48516b
Create Date: 2026-02-07 09:04:59.724074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '872998ef7d19'
down_revision: Union[str, Sequence[str], None] = '3c7a9d48516b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "accounts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("account_type", sa.Enum(
            "ASSET", "LIABILITY", "EQUITY", "INCOME", "EXPENSE",
            name="accounttype"
        ), nullable=False),
        sa.Column("normal_balance", sa.Enum(
            "DEBIT", "CREDIT",
            name="normalbalance"
        ), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("is_posting", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_system_locked", sa.Boolean(), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(["parent_id"], ["accounts.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
        sa.UniqueConstraint("name"),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
